global settings for Video Configuration
AgoraIO/API-Examples pull request #100
Opened 2020-12-15 10:58 UTC by xuchdeid

global settings for Video Configuration

2020-12-15 12:57 UTC, yoreland commented on macOS/APIExample.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = Y695MMFA83;
we could remove project file in commit list

2020-12-16 02:19 UTC, plutoless commented on macOS/APIExample.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = Y695MMFA83;
签名不要改，会影响CI

2020-12-16 02:24 UTC, plutoless commented on macOS/APIExample/Examples/Advanced/CustomVideoSourceMediaIO/CustomVideoSourceMediaIO.swift
> +        resolutionPicker.selectItem(at: GlobalSettings.shared.settings["resolution"]!.selectedOption().value as! Int)
建议用guard let, 少用!

2020-12-16 02:24 UTC, plutoless requested changes
有没有可能把设置做成单独的按钮而不是作为左边菜单里的一部分？现在这样看起来有些奇怪

2020-12-16 16:05 UTC, plutoless approved these changes

2020-12-16 16:05 UTC, merged